name: Set Environment Variable
on:
  push:
    branches:
        master
env: 
  HOME_DIR: ~/
jobs:
  Echo-HOME_DIR:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${{ env.HOME_DIR }}
